package br.com.sysagrega.util;

public interface Constante {

	String VAR_AMBIENTE_DADOS_SISTEMA = "DADOS_SISTEMA"; 
	
    String CLIENTE = "C:/DADOS_SISTEMA/AGREGA/ANEXOS/CLIENTE/";
    String FORNECEDOR = "C:/DADOS_SISTEMA/AGREGA/ANEXOS/FORNECEDOR";
    String CONTRATO = "C:/DADOS_SISTEMA/AGREGA/ANEXOS/CONTRATO";
    String PROJETO = "C:/DADOS_SISTEMA/AGREGA/ANEXOS/PROJETO";
    String PROPOSTA = "C:/DADOS_SISTEMA/AGREGA/ANEXOS/PROPOSTA";
    String PLANEJAMANTO = "C:/DADOS_SISTEMA/AGREGA/ANEXOS/PLANEJAMENTO";
    String PROFISSIONAL = "C:/DADOS_SISTEMA/AGREGA/ANEXOS/PROFISSIONAL";
    
    String MSG_INFO_OPERACAO_REALIZADA_COM_SUCESSO = "Operação realizada com sucesso.";
    
}